### ISSUE TITLE
GetSet that uses php://input?

### ISSUE THREAD

**Issue by jerry1970** [devvoh/parable#23]
You've added `getBody()` to the `Request` in 0.12.7. But I expected a GetSet class reading the body as well. 

There is the abstract class `BaseInput` with the excellent `extractAndSetData()`. Its constructor reads the request body and use `setAll()`.

Now, three classes extend from this: `Patch`, `Put`, and `Delete`. These three have a `$resource` as well, meaning the `setAll()` will not do anything with the values from the body (see the `if` block there).

This means there is no GetSet class actually having the body values. I think this is a bug?

I am using [axios](https://github.com/mzabriskie/axios) for my ajax calls and axios uses a HTTP POST with a body. (Not sure why, though, but I like axios enough to keep using it as it flows nicely with [vue](http://vuejs.org).)

So... I could request the `GetSet\Post` extending `BaseInput` but that would not solve my problem.
Therefore, I think it would be very nice to have something like `GetSet\JsonBody` that extends BaseInput and does not have a `$resource`.

**Comment by devvoh** [comment]
Quick response: `setAll()` _only_ sets values when a resource is set. You seem to be doing the opposite?

**Comment by jerry1970** [comment]
Oops, missed something there... Yes, `setAll()` doest set the `php::/input` contents. But now I need it for a POST. Guess I have to create an extend on the `GetSet\Post` or a new one based on `BaseInput`. Anyway, thanks for pointing out what I got wrong! :stuck_out_tongue:

**Comment by devvoh** [comment]
This feels like a totally valid thing to want to do, but outside of php's default way of working with POST data. Given how there's now 3 `BaseInput` and a bigger handful of `Base` GetSetters, I might look into consolidating the two ways of getting the data in there and perhaps making it configurable.

This would make it possible to tell POST to use (and interpret, like `BaseInput` does) the input stream rather than the default global values.

**Comment by jerry1970** [comment]
Configurable as in I have to choose once? I prefer to have both options all the time so different methods can use POST or body. It's just another way of accepting data, so Input lives next to Post, Put, etc. so I can check myself: if Post is empty I will check for Input.

Or an option that says: if the resource (_POST, etc.) is empty I will check whether the Input is a json.

This is a suggestion, of course. You decide and I'll live with that and build framework-non-essentials around it.

**Comment by devvoh** [comment]
After talking it through over other means, we've come to the conclusion that the split for PUT/PATCH/DELETE is just for style and actually limiting this exact use case.

So the plan is as follows: Remove Put/Patch/Delete GetSetters, and replace them with a straightforward `\Parable\GetSet\InputStream` that can be used for loading the input body and parsing it like `BaseInput` currently does. 

This'll make it far more useful.

**Comment by jerry1970** [comment]
That'll work. To be honest looks nicer at a framework level! It does what it says and nothing more - I like that. Now you leave it up to the devs to create a Put/Patch/Delete GetSetter from the InputStream if they really want it. :)

**Comment by devvoh** [comment]
Completely forgot to close this. Should be fixed in commit f6cdfd58a20d99f2d7397cc8c54cbcc49a77b61a, which was released as 0.12.9.

By now we're already at 0.12.10, which offers `$getSet->get("one.two.three");` functionality as well.

This issue spurred some critical thinking about how the `GetSet` component works, and it's improved as a result :)
