### ISSUE TITLE
More consistency in Parable's default folder names

### ISSUE THREAD

**Issue by FaaPz** [devvoh/parable#6]
**Parable's current application structure:**
- `app/Config`
- `app/Controller`
- `app/Init`
- `app/Model`
- `app/Routes`
- `app/View/Home`

I would love to see this application structure use a singular _or_ plural form with folder naming. I'd prefer plural, but some names aren't made for it. 😜 

What do you think, @devvoh?

**Comment by devvoh** [comment]
I see where you're coming from, and the only 'odd one out' at the moment is `Routes`.

I'd like to hear your reason for preferring plural. My reason to consider plural would be that it implies a collection of, rather than just a single item of. My reason to consider singular is related - plural implies a collection of, but `\Controller\Home` seems to fit better. 

My preference lies in singular, making `Routes` either `Routing` (preferred) or `Route`.

It's a tiny little issue (you'll have to admit) but I can understand that it can 'feel' right or wrong ;)

**Comment by devvoh** [comment]
After thinking about it, I've chosen to stick to singular. As such, `Routes` has been renamed to `Routing` in 0.10.0 / c196abc
