### ISSUE TITLE
Allow multiple route files

### ISSUE THREAD

**Issue by FaaPz** [devvoh/parable#9]
My next project has lots of endpoints, so lots of defined routes. But I don't want to add them all into `Config\App`.

I would really appreciate if you'd made `loadRoutes` working like `Framework\App::loadInits()`.
Or if you thinks that's bloat, maybe two hooks:

- `parable_routing_load_before`
- `parable_routing_load_after`

What do you think @devvoh? :slightly_smiling_face:

**Comment by devvoh** [comment]
Good suggestions!

And I get why, I've had a similar issue, but I haven't gotten around to implementing a proper fix for it yet, since most projects I do in Parable tend to max out at around 20-30 routes or so.

What I've done in those cases is the following, which I can suggest as a work-around:

```
class App extends \Parable\Framework\Routing\Base
{
    /** @var array */
    protected $combinedRoutes = [];

    public function __construct(
        \Routing\Front $routing_front,
        \Routing\Admin $routing_admin,
        \Routing\Dashboard $routing_dashboard
    ) {
        $this->combinedRoutes = array_merge(
            $routing_front->get(),
            $routing_admin->get(),
            $routing_dashboard->get()
        );
    }

    public function get()
    {
        return $this->combinedRoutes;
    }
}
```

`\Routing\App` is DI-ed, so this should work. Mind you, this is a pseudo-code version, I don't have the actual code handy at the moment, but I think you'll see that this could be an option until there's an 'official' way to do it :)

**Comment by devvoh** [comment]
Actually, I'm definitely adding those hooks. In `loadRoutes`, I'll probably just add `parable_routing_load_before` and `parable_routing_load_after` like you suggested. Also a good moment to add hooks to `loadInits` 🙂

**Comment by FaaPz** [comment]
I like the work-around, thanks! 😄
